import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Todone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='h-screen flex justify-center items-center'>
      {children}
    </main>
  );
}
